### ISSUE TITLE
summary stats on X chromosome data are incorrect and simulated SNP data are unrealistic

### ISSUE THREAD

**Issue by fradav** [diyabc/diyabc#1] opened 2019-05-12 17:07 UTC
#https://github.com/cbgp/diyabc/issues/2

I didn't track this, as we rewrote our stats system.

Is this solved in our version?

**Comment by aestoup** [comment] 2020-04-01 15:16
I do not understand this general formulation of the pbl = "summary stats on X chromosome data are incorrect and simulated SNP data are unrealistic"...It seems this is a old formulation of the pbl as we now know more about it = that the problem may be actually a MAF pbl for NON-AUTOSOMAL loci (including mtDNA loci): correct ??????

**Comment by aestoup** [comment] 2020-04-01 15:23
Eric: do you have any evidence of wrong allele frequency computation for SNP located on mtDNA?????

**Comment by fradav** [comment] 2020-04-01 15:29
> Eric: do you have any evidence of wrong allele frequency computation for SNP located on mtDNA?????

This issue was not originated by @elombaert but by @bnsacks on https://github.com/cbgp/diyabc/issues/2

**Comment by aestoup** [comment] 2020-04-01 15:49
Exact !!! Je me melangeais avec les pbl d'eric sur l'ADNmt...en fait ca concerne SNP sur le X: sorry.
Je me souviens de ce vieux mail.
Bon c'est plus compliqué ce truc...il faudra 1/ simuler des raw pseudo-obs pour voir et 2/  rentrer dans le code pour voir si division par N ou 2N...
Je propose de mettre cet issue plutot vers la fin...et si Eric peut confirmer a sa maniere le pbl decrit par le mec ca serait super.

**Comment by aestoup** [comment] 2020-04-01 16:07
Note: Fradav j'ai essayé de mettre en bas dans la liste cet issue (pour inciter a traiter les autres avant) mais je ne vois pas comment cf. glisser déposer ca semble pas marcher: sorry

**Comment by aestoup** [comment] 2020-04-10 10:59
The pbl is due to an erroneous understanding of the user about how to code SNP genoytypes (a conclusion confirmed by looking at the observed and pseudo-obs  datafiles send by the user)...We (Eric and me) have checked that all is ok for various types of datasets that we have simulated (A, Haploide, X, Y mtDNA). We can close this issue.

**Closed as completed** 2020-04-10 10:59 UTC
Labels: invalid, need-repro, simulator, Summary stats
